version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@1.0.0

parameters:
  accounts:
    type: string
    default: "1,2,3"

workflows:
  setup-workflow:
    jobs:
      - setup:
          accounts: << pipeline.parameters.accounts >>

jobs:
  setup:
    docker:
      - image: cimg/base:stable
    parameters:
      accounts:
        type: string
    steps:
      - run:
          name: Generate dynamic config
          command: |
            cat <<EOF > generated_config.yml
version: 2.1

jobs:
  run-bot:
    parameters:
      account:
        type: string
    docker:
      - image: cimg/php:8.2
    steps:
      - checkout
      - run:
          name: Run Captcoin
          command: |
            echo "Running bot for account << parameters.account >>"
            export USERNAME=gtg<< parameters.account >>
            export PASSWORD=memeX3213!
            php captcoin/captcoin.php

workflows:
  run-bots:
    jobs:
EOF
            for acct in $(echo "<< parameters.accounts >>" | tr "," "\n"); do
              echo "      - run-bot:" >> generated_config.yml
              echo "          account: \"$acct\"" >> generated_config.yml
            done

      - continuation/continue:
          configuration_path: generated_config.yml
