name: captcoin.php

on:
  workflow_dispatch:
    inputs:
      numbers:
        description: 'List of account numbers, pisahkan pakai koma'
        required: true
        default: "001,002,003,004,005"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account: ${{ github.event.inputs.numbers.split(',') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Set executable permission
        run: chmod +x captcoin/captcoin.php

      - name: Run Captcoin.php
        run: php captcoin/captcoin.php
        env:
          USERNAME: gtg${{ matrix.account }}
          PASSWORD: memeX3213!
